### ISSUE TITLE
表情没法复读，只能发出文字

### ISSUE THREAD

**Issue by Hanx152** [ninthseason/nonebot-plugin-repeater#10]
如图![(3 SMHZIIXVNQBM8NA6%$QN](https://user-images.githubusercontent.com/103246532/163710005-4c01220a-b848-4c66-ace5-ddc5d6b94e4b.png)

**Comment by ninthseason** [comment]
这是无头QQ的问题，消息上报时就只上报了文字`[阴险]`，插件也无能为力。
![image](https://user-images.githubusercontent.com/29861280/163710996-7ec7a303-b9da-4cbf-bef5-0181df295152.png)

**Comment by Hanx152** [comment]
好吧，谢谢回答
