### ISSUE TITLE
一个下问题，win下不会触发，ubuntu下会触发

### ISSUE THREAD

**Issue by bingganhe123** [ninthseason/nonebot-plugin-repeater#12]
![wenti4](https://user-images.githubusercontent.com/98812723/165469281-128fee08-db8d-43ca-b387-23eafac415d7.png)
ru'tu如图

**Comment by ninthseason** [comment]
应该是默认配置项导致的小问题。已修复。
已更新插件，请再次尝试。

**Comment by bingganhe123** [comment]
收到，感谢
