### ISSUE TITLE
收到指定消息会将机器人卡死

### ISSUE THREAD

**Issue by MTmin** [ninthseason/nonebot-plugin-repeater#15]
…大..群…需要食物……海嗣 诡即将进化………ۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۥۥۥ  ۥۥۥۥۥۥۦۦۥۥۦۥۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۛۚۚۥۥۥ  ۥV^**V^】v我 50块钱…～..**ۥۥۥۥۥۦۦۥۥۦۛۚۗۥjjjjjjjjjĵjjۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۥ…ۥۥ ۥۥۥۥۥۥۦ疯狂！！！星期四！！#**%ۦ ۥۥ

…为..了…登阶……靠近诡道靠近祂………ۦۥۥۦٌۦٌۥۥۚۚۥۥۥۥۥۥۥۥۥ  ۥۥۥۥۥۥۦۦۥۥۦۛۚۗۥۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۛۚۚۥۥۥ      ۥV^**V^】我50…～..**ۥۥۥۥۥۦۦۥۥۦۛۚۗۥjjjjjjjjjĵjjۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۥ肯！德！基…ۥۥ ۥۥۥۥۥۥۦ疯狂！！！星期四！！#**%ۦ ۥۥ…为..了…登阶……靠近诡道靠近祂………ۦۦٌۥۥۚۚۥۥۥۥۥۥۥۥۥ  ۥۥۥۥۥۥۦۦۥۥۦۛۚۗۥۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۛۚۚۥۥۥ     ۥV^**V^】我50…～..**ۥۥۥۥۥۦۦۥۥۦۛۚۗۥjjjjjjjjjĵjjۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۥ肯！德！基…ۥۥ ۥۥۥۥۥۥۦ疯狂！！！星期四！！#**%ۦ ۥۥ…为..了…登阶……靠近诡道靠近祂………ۦۥۥۦٌۦٌۥۥۚۚۥۥۥۥۥۥۥۥۥ ۥۥۥۥۥۥۦۦۥۥۦۛۚۗۥۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۛۚۚۥۥۥ      ۥV^**V^】我50…～..**ۥۥۥۥۥۦۦۥۥۦۛۚۗۥjjjjjjjjjĵjjۥۥۥۖۛۛۦۥۥۦٌۥۥۚۚۥۥۥۥۥۥۥ肯！德！基…ۥۥ ۥۥۥۥۥۥۦ疯狂！！！星期四！！#**%ۦ  ۥۥ…为..了…登阶……靠近诡道靠近祂………ۦۥۥۦٌۦٌۥۥۚۚۥۥۥۥۥۥۥۥۥ   ۥۥۥۥۥۥ

**Comment by MTmin** [comment]
就这条

**Comment by ninthseason** [comment]
我试了没有卡死呀
