### ISSUE TITLE
机器人不复读 是哪一步错了呢

### ISSUE THREAD

**Issue by 1532166579** [ninthseason/nonebot-plugin-repeater#17]
01-01 02:33:10 [SUCCESS] nonebot | NoneBot is initializing...
01-01 02:33:10 [INFO] nonebot | Current Env: dev
01-01 02:33:10 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 10000000.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'repeater_group': ['<all>,'], 'fastapi_reload': True, 'environment': 'dev', 'repeater_min_message_times': 5, 'repeater_min_message_length': 1}
01-01 02:33:10 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-01 02:33:11 [SUCCESS] nonebot | Succeeded to import "echo"
01-01 02:33:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_repeater"
01-01 02:33:11 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
01-01 02:33:11 [SUCCESS] nonebot | Running NoneBot...
01-01 02:33:11 [DEBUG] nonebot | Loaded adapters: OneBot V11
01-01 02:33:11 [INFO] logging | Will watch for changes in these directories: ['C:\\Users\\huai\\QQbot']
01-01 02:33:11 [INFO] logging | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
01-01 02:33:11 [INFO] logging | Started reloader process [23904] using WatchFiles
01-01 02:33:11 [SUCCESS] nonebot | NoneBot is initializing...
01-01 02:33:11 [INFO] nonebot | Current Env: dev
01-01 02:33:11 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 10000000.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'repeater_min_message_length': 1, 'environment': 'dev', 'repeater_group': ['<all>,'], 'fastapi_reload': True, 'repeater_min_message_times': 5}
01-01 02:33:11 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-01 02:33:12 [SUCCESS] nonebot | Succeeded to import "echo"
01-01 02:33:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_repeater"
01-01 02:33:12 [INFO] logging | Started server process [17736]
01-01 02:33:12 [INFO] logging | Waiting for application startup.
01-01 02:33:12 [INFO] logging | Application startup complete.
01-01 02:33:16 [INFO] logging | ('127.0.0.1', 11213) - "WebSocket /onebot/v11/ws/" [accepted]
01-01 02:33:16 [INFO] nonebot | OneBot V11 | Bot 1532166579 connected
01-01 02:33:16 [INFO] logging | connection open
01-01 02:33:17 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message 785603260 from 226746443@[群:786157053] "你好"
01-01 02:33:17 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:17 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:17 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:17 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:18 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -1100200147 from 226746443@[群:786157053] "你好"
01-01 02:33:18 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:18 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:18 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:18 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:18 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:18 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -915703877 from 226746443@[群:786157053] "你好"
01-01 02:33:18 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:18 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:18 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:18 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:18 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:19 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -1448280482 from 226746443@[群:786157053] "你好"
01-01 02:33:19 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:19 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:19 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:19 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:19 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:19 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:19 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -559165752 from 226746443@[群:786157053] "你好"
01-01 02:33:19 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:19 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:19 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:19 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:19 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:19 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:20 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message 1201839986 from 226746443@[群:786157053] "你好"
01-01 02:33:20 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:20 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:20 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:20 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:20 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:20 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:20 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message 816164836 from 226746443@[群:786157053] "你好"
01-01 02:33:20 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:20 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:20 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:20 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:20 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:20 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 02:33:21 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -1363068345 from 226746443@[群:786157053] "你好"
01-01 02:33:21 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 02:33:21 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 02:33:21 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:21 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 02:33:21 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 02:33:21 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete

**Comment by ninthseason** [comment]
群号设置对了吗

**Comment by 1532166579** [comment]
似乎每个第三方插件都不会响应 但是内置的/echo可以 群号尝试过["all"] ["<all>"]都无响应

**Comment by 1532166579** [comment]
重启数次之后问题解决了
01-01 04:22:50 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message 1230972691 from 226746443@[群:786157053] "123"
01-01 04:22:50 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 04:22:50 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 04:22:50 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:50 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:50 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 04:22:50 [DEBUG] nonebot_plugin_repeater | 这一次消息: 123
01-01 04:22:50 [DEBUG] nonebot_plugin_repeater | 上一次消息: 123
01-01 04:22:50 [DEBUG] nonebot_plugin_repeater | 已重复次数: 3/5
01-01 04:22:50 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 04:22:51 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -683953488 from 226746443@[群:786157053] "123"
01-01 04:22:51 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 04:22:51 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 04:22:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:51 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:51 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 这一次消息: 123
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 上一次消息: 123
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 已重复次数: 4/5
01-01 04:22:51 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-01 04:22:51 [SUCCESS] nonebot | OneBot V11 1532166579 | [message.group.normal]: Message -1606647258 from 226746443@[群:786157053] "123"
01-01 04:22:51 [DEBUG] nonebot | Checking for matchers in priority 1...
01-01 04:22:51 [DEBUG] nonebot | Checking for matchers in priority 10...
01-01 04:22:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:51 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-01 04:22:51 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 这一次消息: 123
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 上一次消息: 123
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 已重复次数: 5/5
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 原始的消息: 123
01-01 04:22:51 [DEBUG] nonebot_plugin_repeater | 欲发送信息: 123
01-01 04:22:51 [DEBUG] nonebot | OneBot V11 | Calling API send_group_msg
