### ISSUE TITLE
消息为图片+文字时只能复读图片

### ISSUE THREAD

**Issue by 863109569** [ninthseason/nonebot-plugin-repeater#4]
![Y8_N%8)VQ__2JP9TT6YQZJ8](https://user-images.githubusercontent.com/77315378/151661764-7289306e-827c-4559-9126-9875c337ca00.png)

**Comment by 863109569** [comment]
还有插件没有关注到机器人本身发言对复读的打断作用，目测插件只关注了别人的发言，而没有关注bot的本身发言，这就让bot自己已经打断复读的情况下，仍然复读。。。（其他插件的影响
![}@H{}8)U~1(N{E}S6N1R)OO](https://user-images.githubusercontent.com/77315378/151661917-a1de8642-ef69-4c16-9058-678e8b125ee6.png)

**Comment by ninthseason** [comment]
这是两个相当棘手的问题，我难以快速修复。我会在之后找一个空闲时间修复它。（咕咕）

**Comment by ninthseason** [comment]
已修复第一个问题。
由于未找到监听自身发言的方法，暂未修复第二个问题。

**Comment by ninthseason** [comment]
针对第二个问题：
根据讨论，应该由问答插件进行处理。
因为复读机本身的优先级很低，如果其他插件在复读机运行之前进行了消息阻断，复读机就不会运行。
而问答插件没有进行消息阻断，导致复读机仍然运行。
这个问题不应由复读机进行处理。

**Comment by SakuraPuare** [comment]
> 还有插件没有关注到机器人本身发言对复读的打断作用，目测插件只关注了别人的发言，而没有关注bot的本身发言，这就让bot自己已经打断复读的情况下，仍然复读。。。（其他插件的影响 ![}@H{}8)U~1(N{E}S6N1R)OO](https://user-images.githubusercontent.com/77315378/151661917-a1de8642-ef69-4c16-9058-678e8b125ee6.png)

这个是优先级问题，有个前提是：nonebot是按照 **优先级的数字大小顺序** 从小到大依次对消息进行处理（优先级1>10）。

首先，当你第一次发“。。”的时候，你问我答插件（下称A），回复“。”。而复读机（下称B）记录了你第一次发的“。。”

其次，当你第二次发“。。”的时候，A插件优先级大于B，先运行A插件，nonebot首先回复“。”，接着运行B插件，因为你上一次发送的是“。。”，所以B插件复读“。。”，导致了这样的情况。

解决方案：将A插件设置消息阻断
